mydatabase1: # This is the name of the database as a key. It can be anything.
  description: Optional
  default: Bool[Optional]
  dialect: required. Only accepts 'mysql', 'mssql', 'postgresql', 'oracle', 'sqlite'
  type: sqlalchemy # Optional. Defaults to sqlalchemy. Can choose sqlalchemy or odbc. odbc can support dsn strings.
  uri: None #Required if settings not present. uri for sqlalchemy means connection_uri, uri for odbc means dsn string or connection string.
  settings: #required if uri not present.
    host:
    port:
    username:
    password:
    options: # A dictionary with unknown keys. Pool size is an example.
      pool_size:
  output: dict #Optional. Controls output behavior of the top level json. Any item with multiple rows will automatically be output as a list. 


mysqlitedb: # This is the name of the database as a key. It can be anything.
  type: sqlalchemy #Optional to list as its the only one that will support sqlite. Defaults to sqlalchemy.
  dialect: sqlite # Only path is required for sqlite
  path: required if dialect is sqlite.

    
