mydatabase1:
  description: "My Favorite DB"
  default: True
  dialect: mysql
  interface: sqlalchemy
  uri: "mysql://username:password@localhost:3306/mydatabase1"
  settings:
    orm: False
    auto_commit: False
    paging:
      enabled: True
      auto_page_size: 0
      min_page_size: 0
    one_row_output: dict
    auto_commit: True
mysqlitedb:
  dialect: sqlite
  path: mysqlitedb.db

