app: myapp
name: 'user'
route: /user
doc: optional. If you want to put in documentation.
methods:
  get: 
    args:
    handler: 'get_user' # Name of the handler function.
    handler_path: app.user.get # Optional, will default to location of settings file.
    doc: # Optional, for documentation.
    error:
    model:
  post:
    model:




    





